server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/university_town_tidal_service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.yinxiao.nothing.entity
  configuration:
    map-underscore-to-camel-case: true
    # 驼峰命名
# JWT 配置
jwt:
  secret: jdo+k_703Y#5<ExUl;0CoCmq^;9poP]]b?&i|7{?q{GmWr>T6}P:p*rG1|[fvhv$=Kr:z+eSimq93&++ZHrgi2M/YM\yG0Yi$%P?  # 替换为至少 32 字节的随机字符串
  expiration: 86400000 # 过期时间，单位毫秒

logging:
  level:
    org.yinxiao.nothing: info # 控制项目中特定包的日志级别
    org.yinxiao.nothing.mapper: debug
    org.springframework: info # 控制 Spring 框架的日志级别
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"